### ISSUE TITLE
dataloader missing

### ISSUE THREAD

**Issue by demolakstate** [tufts-ml/GAN-Ensemble-for-Anomaly-Detection#1]
Hello, congratulations on your paper!
Please dataloader is missing in your argument, as shown below:-
---------------
!python train.py \
         --dataset cifar10 \
         --niter 2 \
         --abnormal_class 9 \
         --setting ganomaly \
         --n_G 3 \
         --n_D 3 
-------------
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    main()
  File "train.py", line 23, in main
    model = Ganomaly(opt)
TypeError: __init__() missing 1 required positional argument: 'dataloader'

**Comment by demolakstate** [comment]
I guess I fixed it as follows:-

from dataloader.dataloader import load_data


def main():
    opt = Options().parse()
    setup_dir(opt)
    
    dataloader = load_data(opt)
    
    if opt.setting == "skipgan":
        model = model_skipgan(opt)
    elif opt.setting == 'egbad':
        if opt.dataset != 'KDD99':
            model = egbad_mxn(opt)
        else:
            model = egbad_kdd(opt)
    elif opt.setting == 'f-anogan':
        model = f_anogan(opt)
    elif opt.setting == 'ganomaly':
        model = Ganomaly(opt, dataloader)
    model.train()

**Comment by demolakstate** [comment]
from dataloader.dataloader import load_data


def main():
    opt = Options().parse()
    setup_dir(opt)
    
    dataloader = load_data(opt)
    
    if opt.setting == "skipgan":
        model = model_skipgan(opt)
    elif opt.setting == 'egbad':
        if opt.dataset != 'KDD99':
            model = egbad_mxn(opt)
        else:
            model = egbad_kdd(opt)
    elif opt.setting == 'f-anogan':
        model = f_anogan(opt)
    elif opt.setting == 'ganomaly':
        model = Ganomaly(opt, dataloader)
    model.train()

**Comment by demolakstate** [comment]
You might also need to update the following:
ND to n_D
NG to n_G
dataloader['train'] to dataloader.train etc
For details, please see - https://youtu.be/L2ZkQ0KNwg0

**Comment by demolakstate** [comment]
I have this error with OCT:

RuntimeError: Given groups=1, weight of size 64 3 4 4, expected input[64, 1, 32, 32] to have 3 channels, but got 1 channels instead

**Comment by XUHAN314** [comment]
Thanks for the feedback!
We have fixed most of the issues you mentioned and some other bugs.
For the OCT dataset, please set nc=1, since there is only 1 channel for this dataset. (and set it as 3 for cifar10)
I will close this issue. If there is any other comments, I will reopen it.
